export const COLOMBIAN_CHARACTERS = [
  "Administrador de conjunto que se cree alcalde",
  "Tia que sabe todos los secretos familiares",
  "Tendero que da credito pero nunca olvida",
  "Domiciliario que llego con una historia increible",
  "Guia turistico que improvisa datos historicos",
  "Conductor de buseta con filosofia propia",
  "Vendedora de empanadas con mirada de detective",
  "Entrenador de gimnasio en crisis espiritual",
  "Locutor de radio comunitaria demasiado dramatico",
  "Abogado de barrio que cobra en favores",
  "Profesor que convierte todo en examen sorpresa",
  "Celador que vio demasiado y habla en clave",
  "Influencer costeando una vida que no puede pagar",
  "Candidato al consejo con promesas imposibles",
  "Barbero que tambien es terapeuta informal",
  "Mecanico que diagnostica carros y relaciones",
  "Mesero que ya no cree en la humanidad",
  "Cantante de serenata despechado",
  "Vecina que administra el chisme como empresa",
  "Turista perdido con exceso de confianza",
  "Ciclista que habla como si estuviera narrando una etapa",
  "Reina de fiestas patronales que quiere renunciar",
  "Emprendedor que vende algo que nadie entiende",
  "Portero que decide quien merece entrar al edificio",
  "Concejal de pueblo durante una promesa dificil",
  "Organizador de rifas que nunca entrega el premio",
  "Mama que resuelve emergencias con comida",
  "Papa que cree que todo se arregla con cinta",
  "Primo que vuelve de otro pais hablando raro",
  "DJ de fiesta familiar con complejo de artista",
  "Sacerdote intentando controlar una novena caotica",
  "Notario que habla como villano elegante",
  "Enfermero que ya escucho todas las excusas",
  "Vendedor de playa que no acepta un no amable",
  "Repartidor de volantes con grandes aspiraciones",
  "Presentador de evento que no sabe que evento es",
  "Cliente que cree que siempre tiene la razon y el descuento",
  "Chef de corrientazo con orgullo Michelin",
  "Conductor de chiva que se cree capitan de barco",
  "Lider de grupo familiar de WhatsApp",
  "Aprendiz del SENA excesivamente preparado",
  "Brujita de barrio que ahora atiende por videollamada",
  "Taxista que solo cuenta teorias imposibles",
  "Futbolista retirado que narra su propia vida",
  "Peluquero que corta cabello y reputaciones",
  "Vigilante de museo enamorado de una estatua",
  "Tendera de pueblo que conoce el destino de todos",
  "Organizador de paseo que perdio la lista",
  "Periodista local buscando escandalo en algo minimo",
  "Duenio de finca que exagera cada problema",
];

export const CHARACTER_TRAITS = [
  "Siempre esta intentando vender algo",
  "Convierte cualquier frase en regano",
  "Habla como si estuviera dando un discurso historico",
  "Cree que todos le deben un favor",
  "Se ofende si no le piden consejo",
  "Tiene una solucion absurda para cada problema",
  "Nunca termina una historia sin meter a un primo",
  "Quiere parecer elegante pero se le sale el barrio",
  "Repite refranes que no existen",
  "Todo lo compara con futbol",
  "Cambia de acento cuando se pone nervioso",
  "Tiene miedo de parecer pobre y lo empeora",
  "Se cree famoso aunque nadie lo reconoce",
  "Confunde tecnologia con brujeria",
  "Dramatiza cada inconveniente como telenovela",
  "Siempre esta a punto de llorar por una bobada",
  "Habla bajito solo cuando va a decir lo peor",
  "No sabe guardar secretos pero lo intenta",
  "Cree que esta siendo grabado para un documental",
  "Usa diminutivos cuando esta furioso",
  "Niega lo evidente con una seguridad admirable",
  "Pide rebaja incluso en situaciones inapropiadas",
  "Se enamora de cualquier persona amable",
  "Tiene una rivalidad imaginaria con alguien presente",
  "Quiere dirigir la escena aunque nadie lo nombro",
  "Siempre llega tarde pero exige puntualidad",
  "Habla en frases de audio de WhatsApp",
  "Celebra pequenas victorias como final de mundial",
  "Interpreta todo como senal divina",
  "Cree que el silencio es una provocacion",
  "Da consejos financieros estando endeudado",
  "No puede decir una mentira sin cantar",
  "Tiene un secreto obvio que defiende mal",
  "Siempre culpa al clima, al trafico o a Mercurio",
  "Trata cualquier reunion como si fuera juicio",
  "Se toma demasiado en serio un cargo inventado",
  "Se comunica con indirectas extremadamente directas",
  "Quiere caerle bien a todo el mundo y fracasa",
  "Pide permiso despues de hacer el dano",
  "Hace pausas dramaticas antes de datos inutiles",
];

export function getRandomCharacter(): string {
  return COLOMBIAN_CHARACTERS[Math.floor(Math.random() * COLOMBIAN_CHARACTERS.length)]!;
}

export function getRandomTrait(): string {
  return CHARACTER_TRAITS[Math.floor(Math.random() * CHARACTER_TRAITS.length)]!;
}
