/** Premisas originales tipo "escenas desde un sombrero": cortas, jugables y colombianas. */

const RAPID_PREMISES = [
  "Cosas que nunca deberias decir en una fila de Bancolombia",
  "Frases que arruinan una novena en tres segundos",
  "Lo peor que puede decir un domiciliario antes de entregar la comida",
  "Excusas malas para no pagar la vaca",
  "Cosas que no quieres oir en un TransMilenio lleno",
  "Malos nombres para una areperia elegante",
  "Mensajes de voz que nadie deberia mandar al grupo familiar",
  "Peores frases para conquistar en una tienda de barrio",
  "Cosas que no deberia anunciar el piloto antes de despegar",
  "Titulares de noticias demasiado colombianos para ser verdad",
  "Lo que no quieres escuchar en una consulta con EPS",
  "Confesiones raras durante una misa de siete",
  "Peores formas de pedir rebaja",
  "Cosas que un taxista dice como si fueran leyes de la fisica",
  "Razones absurdas para declarar festivo un lunes",
  "Peores momentos para decir 'yo conozco un atajo'",
  "Cosas que no se dicen en una reunion de conjunto",
  "Respuestas terribles a 'vecino, bajele al volumen'",
  "Lo peor que puede pasar en un paseo de olla",
  "Anuncios honestos de un hotel barato",
  "Cosas que nunca deberian vender en un semaforo",
  "Frases que hacen que una cita se vuelva entrevista laboral",
  "Peores slogans para una campana de alcalde",
  "Cosas que no quieres ver flotando en el ajiaco",
  "Excusas para llegar tarde que solo funcionan en Colombia",
  "Lo que dice una abuela cuando descubre TikTok",
  "Peores consejos para sobrevivir diciembre",
  "Cosas que un perro callejero sabe de politica local",
  "Frases prohibidas en una peluqueria de barrio",
  "Peores formas de saludar a los papas de tu pareja",
  "Anuncios por altavoz que causarian panico en un pueblo",
  "Peores razones para llevar ruana en clima caliente",
  "Cosas que un turista cree que son normales en Colombia",
  "Lo que no deberia decir un guia en Cartagena",
  "Peores respuestas cuando te preguntan 'ya almorzo?'",
  "Confesiones de alguien que no sabe bailar salsa",
  "Peores cosas para decir antes de una serenata",
  "Cosas que no quieres escuchar de un mecanico",
  "Malas ideas para ahorrar en una boda",
  "Peores nombres para un grupo de WhatsApp familiar",
  "Cosas que no deberia narrar un comentarista de futbol",
  "Frases que convierten cualquier comida en pelea familiar",
  "Lo peor que puede decir alguien con microfono abierto",
  "Cosas que nunca deberian tener sabor a arequipe",
  "Peores formas de explicar una deuda",
  "Comentarios que incendian una reunion de vecinos",
  "Cosas que no quieres oir justo antes de subir a escena",
  "Peores premios de una rifa empresarial",
  "Frases que solo dice alguien que no va a pagar",
  "Cosas que no deberia prometer un influencer de finca raiz",
  "Razones absurdas para cancelar un asado",
  "Peores cosas que escribir en una pancarta de bienvenida",
  "Lo que gritaria un vendedor ambulante en Marte",
  "Cosas que no deberia tener una empanada sorpresa",
  "Peores frases para terminar una llamada incomoda",
  "Cosas que suenan romanticas pero son amenazas de tia",
  "Excusas de un DJ que dano la fiesta",
  "Peores formas de pedir silencio en un teatro",
  "Cosas que una arepa diria si pudiera defenderse",
  "Errores de protocolo en una visita presidencial a una tienda",
];

const GROUP_PREMISES = [
  "Escena grupal: una reunion de conjunto donde todos creen ser administradores",
  "Escena grupal: una familia intenta tomarse una foto y nadie mira al mismo lado",
  "Escena grupal: todos son vendedores de playa compitiendo por el mismo turista",
  "Escena grupal: una junta de emergencia para decidir quien puso pasas en la ensalada",
  "Escena grupal: un paseo de olla se convierte en juicio oral",
  "Escena grupal: cada persona trae una version distinta de la misma chiva",
  "Escena grupal: una banda de pueblo ensaya sin saber que cancion toca",
  "Escena grupal: todos quieren ser padrinos de la misma mascota",
  "Escena grupal: una fila se organiza con reglas inventadas por cada persona",
  "Escena grupal: una reunion familiar donde cada secreto sale por accidente",
  "Escena grupal: todos intentan explicar una ruta distinta al mismo perdido",
  "Escena grupal: un comite decide el nombre de una nueva arepa gourmet",
  "Escena grupal: una tienda de barrio negocia con un extraterrestre",
  "Escena grupal: una familia prepara una sorpresa en el apartamento equivocado",
  "Escena grupal: todos creen que son el presentador principal del evento",
  "Escena grupal: una emisora comunitaria entra en crisis en vivo",
  "Escena grupal: un velorio donde nadie conocia al difunto pero todos opinan",
  "Escena grupal: un bus intermunicipal donde cada pasajero trae una emergencia",
  "Escena grupal: una clase de baile donde nadie acepta que no sabe bailar",
  "Escena grupal: una asamblea escolar decide prohibir algo completamente normal",
  "Escena grupal: una familia intenta dividir la cuenta sin calculadora",
  "Escena grupal: todos trabajan en una EPS y ninguno sabe a que ventanilla mandar",
  "Escena grupal: una banda de vallenato rompe justo antes del coro",
  "Escena grupal: un reality colombiano donde el premio es no madrugar",
  "Escena grupal: una oficina descubre que el correo era para otra empresa",
  "Escena grupal: un equipo de futbol de barrio negocia quien trae el balon",
  "Escena grupal: todos interpretan mal una senal de transito",
  "Escena grupal: una familia intenta hacer mercado con presupuesto imposible",
  "Escena grupal: los vecinos hacen una intervencion por exceso de bunuelos",
  "Escena grupal: una tripulacion de avion tiene acento de todas las regiones",
];

const ABSURD_PREMISES = [
  "El presidente de la junta de accion comunal declara independencia del barrio",
  "Una estatua de plaza principal empieza a cobrar arriendo",
  "Un aguacate exige abogado antes de entrar al guacamole",
  "La arepa con queso demanda reconocimiento como patrimonio emocional",
  "Un semaforo se enamora de un ciclista imprudente",
  "Un cajero automatico da consejos de vida antes de entregar plata",
  "El rio Magdalena presenta su hoja de vida para ser alcalde",
  "Una empanada regresa del futuro para advertir sobre el aji",
  "La panela organiza una huelga contra el cafe",
  "Un bus intermunicipal entra en terapia de pareja con una curva",
  "Un sombrero vueltiao se niega a ser souvenir",
  "Una silla rimax cree que es trono real",
  "El recibo de la luz pide perdon, pero no baja",
  "Un vendedor de minutos vuelve como asesor de inteligencia artificial",
  "El arroz con coco revela que siempre quiso ser postre",
  "Una puerta de TransMilenio decide abrirse emocionalmente",
  "La ciclovia dominical invade un lunes por accidente",
  "Un tamal tiene crisis existencial por ser desayuno y almuerzo a la vez",
  "Una nevera de tienda empieza a cobrar cover",
  "La fila del banco desarrolla conciencia colectiva",
  "Un gallo canta a las tres de la tarde por rebeldia artistica",
  "Un bunuelo rueda hasta el Congreso a radicar una queja",
  "Una mochila wayuu predice el clima mejor que el noticiero",
  "El himno del colegio exige regalias",
  "Un ascensor se vuelve chismoso y repite conversaciones",
  "La bolsa de agua de la tienda quiere ser influencer fitness",
  "Un recibo de parqueadero intenta negociar custodia compartida",
  "La bandeja paisa entra a una dieta y todos sospechan",
  "Un parlante de buseta solo reproduce verdades incomodas",
  "Una vaca de paseo de olla se vuelve gerente de logistica",
];

const RESTRICTION_PREMISES = [
  "Restriccion: solo pueden hablar como si estuvieran vendiendo algo en un semaforo",
  "Restriccion: cada frase debe terminar con 'y por eso subio el arriendo'",
  "Restriccion: todos esconden que no entendieron la instruccion",
  "Restriccion: nadie puede usar la palabra 'no'",
  "Restriccion: cada personaje cree que la escena es una entrevista de trabajo",
  "Restriccion: cada vez que alguien se sienta, cambia de opinion",
  "Restriccion: todo se dice como secreto de familia",
  "Restriccion: cada frase debe sonar como consejo de tia",
  "Restriccion: uno habla como noticiero y otro como audio de WhatsApp",
  "Restriccion: todos estan excesivamente orgullosos de una mala idea",
  "Restriccion: nadie puede mirar al personaje que le habla",
  "Restriccion: cada entrada debe parecer comercial de television",
  "Restriccion: la escena empieza normal y se vuelve reunion de vecinos",
  "Restriccion: todos interpretan cumplidos como insultos",
  "Restriccion: cada personaje esta convencido de que esta en otra ciudad",
  "Restriccion: cada frase debe incluir una excusa diferente",
  "Restriccion: solo se puede negociar, nunca aceptar",
  "Restriccion: cada personaje tiene una urgencia absurda pero educada",
  "Restriccion: todo se explica como tutorial mal hecho",
  "Restriccion: uno cree que esta en telenovela y los demas en documental",
  "Restriccion: cada silencio se llena con un refran inventado",
  "Restriccion: cada personaje exagera una palabra distinta",
  "Restriccion: todos hablan como si estuvieran en una llamada con mala senal",
  "Restriccion: la escena debe terminar con una solucion peor que el problema",
  "Restriccion: todos dicen la verdad, pero de la forma mas inconveniente",
  "Restriccion: cada personaje defiende un objeto inutil como si fuera sagrado",
  "Restriccion: todo se decide por votacion improvisada",
  "Restriccion: cada frase debe empezar con 'mi amor, con todo respeto'",
  "Restriccion: nadie puede decir nombres propios",
  "Restriccion: cada personaje cambia de alianza cada treinta segundos",
];

export const PREMISES: string[] = [
  ...RAPID_PREMISES,
  ...GROUP_PREMISES,
  ...ABSURD_PREMISES,
  ...RESTRICTION_PREMISES,
];

export type PremiseCategory = "all" | "rapid" | "group" | "absurd" | "restriction";

export const PREMISE_CATEGORIES: { id: PremiseCategory; label: string }[] = [
  { id: "all", label: "Todas" },
  { id: "rapid", label: "Rapido" },
  { id: "group", label: "Grupal" },
  { id: "absurd", label: "Absurdo" },
  { id: "restriction", label: "Restriccion" },
];

const CATEGORY_MAP: Record<PremiseCategory, string[]> = {
  all: PREMISES,
  rapid: RAPID_PREMISES,
  group: GROUP_PREMISES,
  absurd: ABSURD_PREMISES,
  restriction: RESTRICTION_PREMISES,
};

export function drawRandomPremise(exclude?: string, category: PremiseCategory = "all"): string {
  const pool = CATEGORY_MAP[category].length > 0 ? CATEGORY_MAP[category] : PREMISES;
  if (pool.length === 0) return "Toca para generar una premisa";
  const filtered = exclude && pool.length > 1 ? pool.filter((p) => p !== exclude) : pool;
  return filtered[Math.floor(Math.random() * filtered.length)]!;
}
