/** Premisas originales tipo "escenas desde un sombrero": simples, generales y faciles de jugar. */

const GENERAL_PREMISES = [
  "Cosas que no deberias decir en una entrevista de trabajo",
  "Peores frases para romper el hielo",
  "Malas formas de pedir un favor",
  "Cosas que no quieres oir en un ascensor lleno",
  "Peores excusas para llegar tarde",
  "Frases que arruinan una primera cita",
  "Cosas que no deberia decir un mesero",
  "Peores formas de pedir la cuenta",
  "Cosas que no quieres escuchar antes de una cirugia",
  "Malos consejos para ahorrar dinero",
  "Peores nombres para un restaurante",
  "Cosas que no deberias decir con un microfono abierto",
  "Peores frases para vender un producto",
  "Cosas que nadie quiere oir en una reunion",
  "Malas maneras de disculparse",
  "Peores respuestas a un cumplido",
  "Cosas que no deberia decir un entrenador personal",
  "Peores formas de terminar una conversacion",
  "Cosas que no quieres que diga un piloto",
  "Malos consejos para cuidar una planta",
  "Peores cosas para decir en un silencio incomodo",
  "Frases que hacen sospechoso a cualquiera",
  "Cosas que no deberian anunciar por altavoz",
  "Peores ideas para una campana publicitaria",
  "Malas razones para cancelar un evento",
  "Cosas que no quieres oir en un hotel",
  "Peores formas de saludar a alguien importante",
  "Cosas que no deberia decir un doctor distraido",
  "Peores mensajes para mandar por error",
  "Malos consejos para verse profesional",
  "Cosas que no quieres escuchar en una videollamada",
  "Peores formas de pedir prestado dinero",
  "Cosas que suenan romanticas pero no lo son",
  "Peores motivos para renunciar el primer dia",
  "Malas frases para empezar un discurso",
  "Cosas que no deberia decir un abogado en juicio",
  "Peores formas de presentar una idea",
  "Cosas que no quieres ver en tu comida",
  "Malos consejos para hacer ejercicio",
  "Peores razones para hacerse famoso",
  "Cosas que no deberias decir en una tienda elegante",
  "Peores formas de evitar una pregunta",
  "Malas frases para cerrar un negocio",
  "Cosas que no quieres oir cuando se va la luz",
  "Peores instrucciones en un manual",
  "Cosas que nadie deberia prometer",
  "Malas formas de parecer inteligente",
  "Peores frases para decir antes de cantar",
  "Cosas que no quieres escuchar en una peluqueria",
  "Peores excusas para no contestar el telefono",
  "Malas ideas para una aplicacion movil",
  "Cosas que no deberia decir un guia turistico",
  "Peores formas de pedir silencio",
  "Cosas que no quieres escuchar en un taxi",
  "Malos consejos para una primera impresion",
  "Peores formas de celebrar antes de tiempo",
  "Cosas que no deberia decir un vendedor insistente",
  "Peores frases para una foto grupal",
  "Malas formas de ganar confianza",
  "Cosas que no quieres oir justo antes de subir a escena",
];

const RAPID_PREMISES = [
  "Cosas que nunca deberias decir en una fila",
  "Lo peor que puede decir un domiciliario antes de entregar la comida",
  "Excusas malas para no pagar",
  "Cosas que no quieres oir en transporte publico",
  "Malos nombres para una cafeteria elegante",
  "Peores frases para conquistar",
  "Cosas que no deberia anunciar el piloto antes de despegar",
  "Titulares de noticias demasiado raros para ser verdad",
  "Lo que no quieres escuchar en una consulta medica",
  "Peores formas de pedir rebaja",
  "Cosas que un conductor dice como si fueran leyes de la fisica",
  "Peores momentos para decir 'yo conozco un atajo'",
  "Cosas que no se dicen en una reunion de vecinos",
  "Respuestas terribles a 'bajale al volumen'",
  "Anuncios honestos de un hotel barato",
  "Cosas que nunca deberian vender en la calle",
  "Frases que hacen que una cita se vuelva entrevista laboral",
  "Peores slogans para una campana politica",
  "Excusas para llegar tarde que casi funcionan",
  "Frases prohibidas en una peluqueria",
  "Cosas que no deberia narrar un comentarista de futbol",
  "Lo peor que puede decir alguien con microfono abierto",
  "Peores formas de explicar una deuda",
  "Comentarios que incendian una reunion",
  "Peores premios de una rifa empresarial",
  "Frases que solo dice alguien que no va a pagar",
  "Cosas que no deberia prometer un influencer",
  "Peores cosas que escribir en una pancarta de bienvenida",
  "Cosas que no deberia tener una empanada sorpresa",
  "Peores frases para terminar una llamada incomoda",
  "Excusas de un DJ que dano la fiesta",
  "Peores formas de pedir silencio en un teatro",
  "Errores de protocolo en una visita importante",
  "Cosas que no quieres leer en una resena de restaurante",
  "Peores frases para decir en un brindis",
  "Cosas que no deberia decir un profesor sustituto",
  "Malas formas de pedir perdon",
  "Peores respuestas a 'tenemos que hablar'",
  "Cosas que no quieres escuchar de un mecanico",
  "Peores formas de salir de una conversacion",
];

const GROUP_PREMISES = [
  "Escena grupal: una reunion de vecinos donde todos creen tener la razon",
  "Escena grupal: todos intentan tomarse una foto y nadie coordina",
  "Escena grupal: varios vendedores compiten por el mismo cliente",
  "Escena grupal: una fila se organiza con reglas inventadas por cada persona",
  "Escena grupal: todos intentan explicar una ruta distinta al mismo perdido",
  "Escena grupal: un comite decide el nombre de un nuevo restaurante",
  "Escena grupal: todos creen que son el presentador principal del evento",
  "Escena grupal: una emisora comunitaria entra en crisis en vivo",
  "Escena grupal: un bus donde cada pasajero trae una emergencia",
  "Escena grupal: una clase de baile donde nadie acepta que no sabe bailar",
  "Escena grupal: todos trabajan en atencion al cliente y nadie sabe la respuesta",
  "Escena grupal: una oficina descubre que el correo era para otra empresa",
  "Escena grupal: un equipo negocia quien trae el balon",
  "Escena grupal: todos interpretan mal una senal de transito",
  "Escena grupal: un grupo intenta hacer mercado con presupuesto imposible",
  "Escena grupal: los vecinos hacen una intervencion por exceso de ruido",
  "Escena grupal: una tripulacion de avion no se pone de acuerdo",
  "Escena grupal: una reunion que pudo ser un correo se vuelve ceremonia",
  "Escena grupal: todos llegaron al lugar equivocado pero nadie quiere admitirlo",
  "Escena grupal: un restaurante intenta atender una mesa imposible",
  "Escena grupal: varios candidatos prometen arreglar un problema minimo",
  "Escena grupal: todos dan instrucciones distintas para armar una silla",
  "Escena grupal: una rueda de prensa donde nadie sabe que paso",
  "Escena grupal: un grupo de amigos intenta decidir donde comer",
  "Escena grupal: una celebracion empieza antes de saber que se celebra",
  "Escena grupal: un equipo de trabajo practica una presentacion sin prepararse",
  "Escena grupal: todos creen que son expertos en un tema que no conocen",
  "Escena grupal: una sala de espera se convierte en competencia",
  "Escena grupal: varios testigos cuentan versiones incompatibles",
  "Escena grupal: un grupo intenta guardar un secreto y falla de inmediato",
];

const RESTRICTION_PREMISES = [
  "Restriccion: solo pueden hablar como vendedores",
  "Restriccion: cada frase debe terminar con 'y por eso llegue tarde'",
  "Restriccion: todos esconden que no entendieron la instruccion",
  "Restriccion: nadie puede usar la palabra 'no'",
  "Restriccion: cada personaje cree que la escena es una entrevista de trabajo",
  "Restriccion: cada vez que alguien se sienta, cambia de opinion",
  "Restriccion: todo se dice como secreto importante",
  "Restriccion: uno habla como noticiero y otro como audio de WhatsApp",
  "Restriccion: todos estan excesivamente orgullosos de una mala idea",
  "Restriccion: nadie puede mirar al personaje que le habla",
  "Restriccion: cada entrada debe parecer comercial de television",
  "Restriccion: la escena empieza normal y se vuelve reunion de vecinos",
  "Restriccion: todos interpretan cumplidos como insultos",
  "Restriccion: cada personaje esta convencido de que esta en otra ciudad",
  "Restriccion: cada frase debe incluir una excusa diferente",
  "Restriccion: solo se puede negociar, nunca aceptar",
  "Restriccion: cada personaje tiene una urgencia pequena pero exagerada",
  "Restriccion: todo se explica como tutorial mal hecho",
  "Restriccion: uno cree que esta en telenovela y los demas en documental",
  "Restriccion: cada silencio se llena con un refran inventado",
  "Restriccion: todos hablan como si estuvieran en una llamada con mala senal",
  "Restriccion: la escena debe terminar con una solucion peor que el problema",
  "Restriccion: todos dicen la verdad, pero de la forma mas inconveniente",
  "Restriccion: todo se decide por votacion improvisada",
  "Restriccion: nadie puede decir nombres propios",
  "Restriccion: cada personaje cambia de alianza cada treinta segundos",
  "Restriccion: todo se habla en susurros dramaticos",
  "Restriccion: cada personaje quiere irse pero necesita quedarse",
  "Restriccion: cada frase debe sonar como una disculpa falsa",
  "Restriccion: nadie puede terminar sus propias frases",
];

export const PREMISES: string[] = [
  ...GENERAL_PREMISES,
  ...RAPID_PREMISES,
  ...GROUP_PREMISES,
  ...RESTRICTION_PREMISES,
];

export type PremiseCategory = "all" | "general" | "rapid" | "group" | "restriction";

export const PREMISE_CATEGORIES: { id: PremiseCategory; label: string }[] = [
  { id: "all", label: "Todas" },
  { id: "general", label: "General" },
  { id: "rapid", label: "Rapido" },
  { id: "group", label: "Grupal" },
  { id: "restriction", label: "Restriccion" },
];

const CATEGORY_MAP: Record<PremiseCategory, string[]> = {
  all: PREMISES,
  general: GENERAL_PREMISES,
  rapid: RAPID_PREMISES,
  group: GROUP_PREMISES,
  restriction: RESTRICTION_PREMISES,
};

export function drawRandomPremise(exclude?: string, category: PremiseCategory = "all"): string {
  const pool = CATEGORY_MAP[category].length > 0 ? CATEGORY_MAP[category] : PREMISES;
  if (pool.length === 0) return "Toca para generar una premisa";
  const filtered = exclude && pool.length > 1 ? pool.filter((p) => p !== exclude) : pool;
  return filtered[Math.floor(Math.random() * filtered.length)]!;
}
