/** Premisas rapidas originales: simples, comicas y listas para jugar. */

const HAND_PICKED_PREMISES = [
  "Peores frases para empezar una entrevista de trabajo",
  "Cosas que no deberias decir con un microfono abierto",
  "Excusas malas para llegar tarde",
  "Peores formas de pedir perdon",
  "Cosas que no quieres oir antes de una cirugia",
  "Malos consejos para una primera cita",
  "Peores nombres para un restaurante elegante",
  "Cosas que no deberia decir un piloto",
  "Frases que convierten una reunion en pelea",
  "Peores formas de pedir la cuenta",
  "Cosas que no quieres escuchar en un ascensor lleno",
  "Malas maneras de parecer profesional",
  "Peores mensajes para mandar por error",
  "Cosas que no deberia decir un mesero",
  "Peores slogans para una campana politica",
  "Excusas para no contestar el telefono",
  "Cosas que no quieres escuchar de un mecanico",
  "Peores respuestas a un cumplido",
  "Malas frases para vender algo usado",
  "Cosas que no deberias decir en una tienda cara",
  "Peores formas de terminar una llamada incomoda",
  "Cosas que hacen sospechoso a cualquiera",
  "Malos consejos para ahorrar dinero",
  "Peores cosas para decir en un silencio incomodo",
  "Cosas que no deberia anunciar un altavoz",
  "Peores ideas para una aplicacion movil",
  "Malas razones para cancelar un evento",
  "Cosas que no quieres oir en un hotel barato",
  "Peores formas de saludar a alguien importante",
  "Cosas que no deberia decir un doctor distraido",
  "Malos consejos para cuidar una planta",
  "Peores frases para romper el hielo",
  "Cosas que no quieres escuchar en una videollamada",
  "Peores formas de pedir prestado dinero",
  "Cosas que suenan romanticas pero no lo son",
  "Peores motivos para renunciar el primer dia",
  "Malas frases para empezar un discurso",
  "Cosas que no deberia decir un abogado en juicio",
  "Peores formas de presentar una idea",
  "Cosas que no quieres ver en tu comida",
  "Malos consejos para hacer ejercicio",
  "Peores razones para hacerse famoso",
  "Peores formas de evitar una pregunta directa",
  "Malas frases para cerrar un negocio",
  "Cosas que no quieres oir cuando se va la luz",
  "Peores instrucciones en un manual",
  "Cosas que nadie deberia prometer",
  "Peores frases para decir antes de cantar",
  "Cosas que no quieres escuchar en una peluqueria",
  "Cosas que no deberia decir un guia turistico",
  "Peores formas de pedir silencio",
  "Cosas que no quieres escuchar en un taxi",
  "Malos consejos para una primera impresion",
  "Peores formas de celebrar antes de tiempo",
  "Cosas que no deberia decir un vendedor insistente",
  "Peores frases para una foto grupal",
  "Malas formas de ganar confianza",
  "Cosas que no quieres oir justo antes de subir a escena",
  "Lo peor que puede decir un domiciliario antes de entregar la comida",
  "Excusas malas para no pagar",
  "Cosas que no quieres oir en transporte publico",
  "Malos nombres para una cafeteria moderna",
  "Peores frases para conquistar",
  "Titulares de noticias demasiado raros para ser verdad",
  "Lo que no quieres escuchar en una consulta medica",
  "Peores formas de pedir rebaja",
  "Cosas que un conductor dice como si fueran leyes de la fisica",
  "Peores momentos para decir yo conozco un atajo",
  "Cosas que no se dicen en una reunion de vecinos",
  "Respuestas terribles a bajale al volumen",
  "Anuncios honestos de un hotel barato",
  "Cosas que nunca deberian vender en la calle",
  "Frases que hacen que una cita se vuelva entrevista laboral",
  "Excusas para llegar tarde que casi funcionan",
  "Frases prohibidas en una peluqueria",
  "Cosas que no deberia narrar un comentarista de futbol",
  "Lo peor que puede decir alguien con microfono abierto",
  "Peores formas de explicar una deuda",
  "Comentarios que incendian una reunion",
  "Peores premios de una rifa empresarial",
  "Frases que solo dice alguien que no va a pagar",
  "Cosas que no deberia prometer un influencer",
  "Peores cosas que escribir en una pancarta de bienvenida",
  "Cosas que no deberia tener una empanada sorpresa",
  "Excusas de un DJ que dano la fiesta",
  "Peores formas de pedir silencio en un teatro",
  "Errores de protocolo en una visita importante",
  "Cosas que no quieres leer en una resena de restaurante",
  "Peores frases para decir en un brindis",
  "Cosas que no deberia decir un profesor sustituto",
  "Peores respuestas a tenemos que hablar",
  "Peores formas de salir de una conversacion",
  "Cosas que no deberia decir alguien vendiendo rifas",
  "Peores cosas para decir al recibir un regalo feo",
  "Malas formas de anunciar una sorpresa",
  "Cosas que no quieres escuchar de quien cocina",
  "Peores formas de pedir ayuda",
  "Frases que convierten un favor pequeno en problema grande",
  "Cosas que no deberia decir el encargado de seguridad",
  "Peores ideas para ahorrar tiempo",
  "Malas respuestas a una pregunta sencilla",
  "Cosas que no quieres oir de una persona con tijeras",
  "Peores formas de explicar que perdiste algo",
  "Cosas que no deberia decir un jurado",
  "Malas frases para calmar a alguien",
  "Peores formas de improvisar una disculpa",
  "Cosas que no quieres escuchar de un entrenador de baile",
  "Peores ideas para una cita economica",
  "Malas razones para cambiar de nombre",
  "Cosas que no deberias decir cuando todos estan mirando",
  "Peores formas de fingir que entendiste",
  "Frases que hacen incomodo un almuerzo",
  "Cosas que no quieres oir de un tecnico de internet",
  "Peores formas de pedir permiso",
  "Cosas que no deberia decir una persona perdida",
  "Malos consejos para hacer amigos",
  "Peores formas de recomendar una pelicula",
  "Cosas que no quieres escuchar de un fotografo",
  "Peores formas de reaccionar a un chiste malo",
  "Frases que arruinan cualquier aplauso",
  "Cosas que no deberia decir un cajero",
  "Peores excusas para cancelar a ultima hora",
  "Malas ideas para llamar la atencion",
  "Cosas que no quieres escuchar antes de una prueba",
  "Peores formas de dar una mala noticia",
  "Frases que delatan que no sabes lo que haces",
  "Cosas que no deberia decir el presentador de un evento",
  "Peores formas de vender confianza",
  "Malas respuestas cuando te piden referencias",
  "Cosas que no quieres oir en una sala de espera",
  "Peores frases para decir frente a un jefe",
  "Cosas que no deberia decir un entrenador antes del partido",
  "Malas formas de explicar una mancha",
  "Peores maneras de pedir que te devuelvan algo",
  "Cosas que no quieres escuchar en una audicion",
  "Frases que hacen que una fila se vuelva caos",
  "Peores consejos de moda",
  "Cosas que no deberia decir una persona con un megafono",
  "Malas formas de vender comida saludable",
  "Peores respuestas a quien es usted",
  "Cosas que no quieres escuchar durante una clase de manejo",
  "Peores formas de iniciar una amistad",
  "Frases que hacen que todos miren al suelo",
  "Cosas que no deberia decir un anfitrion",
  "Malas excusas para no bailar",
  "Peores formas de explicar una compra impulsiva",
  "Cosas que no quieres oir antes de firmar un contrato",
  "Peores frases para decir con cara seria",
  "Malas ideas para una promocion dos por uno",
  "Cosas que no deberia decir quien corta el pastel",
  "Peores formas de pedir paciencia",
  "Frases que hacen sospechoso un regalo",
  "Cosas que no quieres escuchar en una cita medica virtual",
  "Malos consejos para cuidar un secreto",
  "Peores formas de pedir una segunda oportunidad",
  "Cosas que no deberia decir un arbitro",
  "Frases que arruinan una entrada dramatica",
  "Peores maneras de fingir sorpresa",
  "Cosas que no quieres oir cuando alguien dice confia en mi",
];

const QUICK_CONTEXTS = [
  "en una entrevista de trabajo",
  "en un ascensor lleno",
  "en una primera cita",
  "en una reunion de vecinos",
  "en una videollamada laboral",
  "en la fila del banco",
  "en una peluqueria",
  "en un taxi nocturno",
  "en una sala de espera",
  "en un restaurante elegante",
  "en un restaurante barato",
  "en una tienda de barrio",
  "en una oficina publica",
  "en una clase de baile",
  "en una audicion",
  "en una boda",
  "en un brindis",
  "en una reunion importante",
  "en una llamada con el jefe",
  "en una cita medica",
  "en una clase de manejo",
  "en una prueba de talento",
  "en una foto grupal",
  "en un hotel",
  "en un aeropuerto",
  "en una entrevista de television",
  "en una rueda de prensa",
  "en un gimnasio",
  "en una tienda elegante",
  "en un supermercado",
  "en una farmacia",
  "en una notaria",
  "en una porteria",
  "en un parqueadero",
  "en un teatro",
  "en una cabina de radio",
  "en una reunion que pudo ser un correo",
  "en una fiesta sin musica",
  "en una clase sorpresa",
  "en una competencia de cocina",
  "en un concurso de baile",
  "en una venta de garaje",
  "en una cena formal",
  "en una sala de juntas",
  "en un evento con poco presupuesto",
  "en un discurso de bienvenida",
  "en una entrevista para un cargo inventado",
  "en una llamada de servicio al cliente",
  "en un consultorio odontologico",
  "en una clase de yoga",
  "en una tienda de tecnologia",
  "en una reunion de exalumnos",
  "en una entrega de premios pequena",
  "en un casting improvisado",
  "en una fila que no avanza",
  "en un bus con afan",
  "en un ensayo general",
  "en una demostracion de producto",
  "en una cita a ciegas",
  "en una inauguracion sin invitados",
  "en una llamada con mala senal",
  "en un taller mecanico",
  "en una cafeteria llena",
  "en una entrevista para ser mascota corporativa",
  "en una reunion secreta poco secreta",
  "en una despedida incomoda",
  "en una celebracion prematura",
  "en una clase donde nadie estudio",
  "en un viaje de grupo",
  "en una mesa donde nadie quiere pagar",
];

const QUICK_FRAMES = [
  "Cosas que no deberias decir {context}",
  "Lo peor que alguien puede confesar {context}",
  "Frases que vuelven incomodo todo {context}",
  "Senales de que algo va muy mal {context}",
];

const GENERATED_PREMISES = QUICK_CONTEXTS.flatMap((context) =>
  QUICK_FRAMES.map((frame) => frame.replace("{context}", context))
);

export const PREMISES: string[] = Array.from(
  new Set([...HAND_PICKED_PREMISES, ...GENERATED_PREMISES])
);

export function drawRandomPremise(exclude?: string | string[]): string {
  const blocked = new Set(Array.isArray(exclude) ? exclude : exclude ? [exclude] : []);
  const pool = PREMISES.filter((premise) => !blocked.has(premise));
  const source = pool.length > 0 ? pool : PREMISES;
  return source[Math.floor(Math.random() * source.length)] ?? "Toca para generar una premisa";
}
